### ISSUE TITLE
Problem installing the OTF in Windows 7 Enterprise

### ISSUE THREAD

**Issue by notabene** [Orange-OpenSource/font-accessible-dfa#1]
Hi there.

I tried to use the OTF in Windows 7 Enterprise (AKA eburo, Orange's flavour of Windows) and the font manager said:

![screenshot, plain text description below this image](https://cloud.githubusercontent.com/assets/664145/20174933/abf10826-a740-11e6-96a8-bf376d5efb10.png)

“The file is not a valid font file.”

For what it's worth, the TTF installed perfectly.

**Comment by denischene** [comment]
That seems to be a specific Orange's security issue as it works well on other Windows 7 Enterprise non-eburo-Orange OS.
I will up this to the eburo team.
Regards

**Comment by notabene** [comment]
Thank you Denis. I'll try it on my Ubuntu at home soon, let me know if I forget to track down here whether it worked or not.

**Comment by ghost** [comment]
(I think we'll close the issue now as it's been solved) ;)
