### ISSUE TITLE
Font aliasing for lower-case: had to distingish between lower-case L and I

### ISSUE THREAD

**Issue by notabene** [Orange-OpenSource/font-accessible-dfa#16]
Hi @denischene 

Due to (I guess) font aliasing in Windows, I can't see the difference between lower-case L (as in “help”) and I (as in “side”).

Improvement suggestion: increse the space between vertical bar and dot.

See enclosed image:
![the word “client”](https://github.com/user-attachments/assets/bd659957-b669-4159-8e3c-ae7a478d6e9a)

**Comment by denischene** [comment]
![Image](https://github.com/user-attachments/assets/b9a26676-983a-4f4c-a1b2-06e41292b43d)
it seems better like this, isn’t it ? (size4 in Word)
