### ISSUE TITLE
Font installation on linux

### ISSUE THREAD

**Issue by notabene** [Orange-OpenSource/font-accessible-dfa#3]
Hi Denis,

In the README I see:

> To download and install the free Accessible-DfA font for Linux (GNOME): Open “Places” (nautilus), then type in file:///, then drag the “AccessibleDfA.otf” font file.

I think in Gnome you have to go to the fonts folder, which is either system-wide or personal. In this latter case, it's located at `~/.fonts` (`~` being your user's home folder) and does not exist by default.

So I would modify as such, for a per-person install:

1. In Nautilus, display all hidden files and folders
2. find a folder named `.fonts` — if it does not exist, create it
3. drag the “AccessibleDfA.otf” font file into the folder
4. if needed, restart your word processor to see the Accessible DfA font in your font list

I can also provide a tutorial for system-wide install if needed.

**Comment by denischene** [comment]
Thanks, I’ve corrected the readme file.
