### ISSUE TITLE
Consider variable fonts

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/font-accessible-dfa#4]
~~`woff2` file format is a _de facto_ standard for years now due to [its excellent browser support](https://caniuse.com/woff2).~~

Moreover, it enables [variable fonts support](https://caniuse.com/variable-fonts) too, meaning a single file could host every variations— I even made [a Boosted example a few years ago using Helvetica Now](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/640), the variable version for Helvetica Neue.

Could help reduce the font footprint and ease its adoption. :)

**Comment by ffoodd** [comment]
Just saw `.woff2` files arer already served, my bad. Keeping this opened to consider variable font though.

**Comment by denischene** [comment]
Done. New variable font 2.0 version
